# Generated by Django 3.2.16 on 2026-04-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_plan_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='comment',
            field=models.CharField(default='', max_length=100),
        ),
    ]
